repos:
  - repo: local
    hooks:
      - id: pytest
        name: Run Pytest
        entry: uv run pytest
        language: system
        pass_filenames: false
        always_run: true
        types: [python]
        stages: [pre-push]